apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: yvfcexqon-nodejs 
  janus-idp.io/tekton: yvfcexqon-nodejs
  backstage.io/kubernetes-id: yvfcexqon-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yvfcexqon-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml